from __future__ import annotations

from typing import Any

from psycopg.types.json import Jsonb

from .db import execute, fetch_all
from .email_templates import render_all_samples


BANNED_PUBLIC_TERMS = [
    "chatgpt",
    "codex",
    "ai-built",
    "built by ai",
    "generated by ai",
    "autonomous agent",
    "autonomous ai",
    "llm",
    "prompt",
    "prototype",
    "debug",
    "lorem ipsum",
    "placeholder",
]
RISKY_PUBLIC_CLAIMS = [
    "we hacked",
    "we scanned your security",
    "security breach",
    "exploit",
    "malware",
    "vulnerability found",
    "urgent security",
]


def check_no_ai_public_language(samples: list[dict[str, str]] | None = None, scope: str = "templates") -> dict[str, Any]:
    items: list[dict[str, str]] = samples or [
        {"name": f"email:{item['template_key']}:{item['language']}", "text": f"{item['subject']}\n{item['text']}"}
        for item in render_all_samples()
    ]
    issues: list[dict[str, Any]] = []
    for item in items:
        lower = item["text"].lower()
        for term in BANNED_PUBLIC_TERMS:
            if term in lower:
                issues.append({"item": item["name"], "term": term})
    row = execute(
        "INSERT INTO public_language_gate_runs(scope, status, issues_json) VALUES (%s, %s, %s) RETURNING *",
        (scope, "pass" if not issues else "fail", Jsonb(issues)),
    )
    return dict(row)


def _default_public_copy_samples(limit: int = 100) -> list[dict[str, str]]:
    safe_limit = max(1, min(int(limit or 100), 250))
    items: list[dict[str, str]] = [
        {"name": f"email:{item['template_key']}:{item['language']}", "text": f"{item['subject']}\n{item['text']}\n{item.get('html', '')}"}
        for item in render_all_samples()
    ]
    for row in fetch_all(
        """
        SELECT public_slug, summary
        FROM audits
        WHERE COALESCE(summary, '') <> ''
        ORDER BY created_at DESC
        LIMIT %s
        """,
        (safe_limit,),
    ):
        items.append({"name": f"audit:{row['public_slug']}", "text": row["summary"] or ""})
    for row in fetch_all(
        """
        SELECT ai.issue_type, ai.title, ai.public_text, ai.recommendation, a.public_slug
        FROM audit_issues ai
        JOIN audits a ON a.id = ai.audit_id
        ORDER BY ai.created_at DESC
        LIMIT %s
        """,
        (safe_limit,),
    ):
        items.append(
            {
                "name": f"audit_issue:{row['public_slug']}:{row['issue_type']}",
                "text": "\n".join([row.get("title") or "", row.get("public_text") or "", row.get("recommendation") or ""]),
            }
        )
    for row in fetch_all(
        """
        SELECT id, subject, body, html_body
        FROM outreach_messages
        WHERE status IN ('preview', 'queued')
        ORDER BY created_at DESC
        LIMIT %s
        """,
        (safe_limit,),
    ):
        items.append({"name": f"outreach_preview:{row['id']}", "text": "\n".join([row.get("subject") or "", row.get("body") or "", row.get("html_body") or ""])})
    return items


def check_public_copy_quality(samples: list[dict[str, str]] | None = None, scope: str = "public_copy", limit: int = 100) -> dict[str, Any]:
    items = samples if samples is not None else _default_public_copy_samples(limit)
    issues: list[dict[str, Any]] = []
    for item in items:
        text = item.get("text") or ""
        lower = text.lower()
        for term in BANNED_PUBLIC_TERMS:
            if term in lower:
                issues.append({"item": item["name"], "code": "banned_operator_language", "term": term})
        for phrase in RISKY_PUBLIC_CLAIMS:
            if phrase in lower:
                issues.append({"item": item["name"], "code": "risky_public_claim", "term": phrase})
        if "{{" in text or "}}" in text:
            issues.append({"item": item["name"], "code": "unresolved_template_var"})
        stripped = text.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            issues.append({"item": item["name"], "code": "raw_json_visible"})
    row = execute(
        "INSERT INTO public_language_gate_runs(scope, status, issues_json) VALUES (%s, %s, %s) RETURNING *",
        (scope, "pass" if not issues else "fail", Jsonb(issues[:100])),
    )
    result = dict(row)
    result.update(
        {
            "decision": "PASS_PUBLIC_COPY_GATE" if not issues else "FAIL_PUBLIC_COPY_GATE",
            "sample_count": len(items),
            "issue_count": len(issues),
            "send_mail": False,
            "smtp_called": False,
            "live_outreach_allowed": False,
            "raw_recipient_addresses_included": False,
            "secrets_included": False,
        }
    )
    return result
