from __future__ import annotations

from typing import Any

from psycopg.types.json import Jsonb

from .db import execute
from .email_templates import render_all_samples


BANNED_PUBLIC_TERMS = [
    "chatgpt",
    "codex",
    "ai-built",
    "built by ai",
    "generated by ai",
    "autonomous agent",
    "llm",
    "prompt",
]


def check_no_ai_public_language(samples: list[dict[str, str]] | None = None, scope: str = "templates") -> dict[str, Any]:
    items: list[dict[str, str]] = samples or [
        {"name": f"email:{item['template_key']}:{item['language']}", "text": f"{item['subject']}\n{item['text']}"}
        for item in render_all_samples()
    ]
    issues: list[dict[str, Any]] = []
    for item in items:
        lower = item["text"].lower()
        for term in BANNED_PUBLIC_TERMS:
            if term in lower:
                issues.append({"item": item["name"], "term": term})
    row = execute(
        "INSERT INTO public_language_gate_runs(scope, status, issues_json) VALUES (%s, %s, %s) RETURNING *",
        (scope, "pass" if not issues else "fail", Jsonb(issues)),
    )
    return dict(row)
