from __future__ import annotations

import json
import os
from typing import Any

from psycopg.types.json import Jsonb

from .db import connect
from .scanner import safe_public_scan


def claim_scanner_job() -> dict[str, Any] | None:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                WITH picked AS (
                  SELECT id
                  FROM scanner_jobs
                  WHERE status = 'queued'
                  ORDER BY priority ASC, queued_at ASC
                  FOR UPDATE SKIP LOCKED
                  LIMIT 1
                )
                UPDATE scanner_jobs
                SET status = 'running', started_at = now(), updated_at = now()
                FROM picked
                WHERE scanner_jobs.id = picked.id
                RETURNING scanner_jobs.id, scanner_jobs.url, scanner_jobs.business_name, scanner_jobs.dry_run
                """
            )
            row = cur.fetchone()
        conn.commit()
    return dict(row) if row else None


def _summary(result: dict[str, Any]) -> str:
    issues = result.get("issues") or []
    if not issues:
        return "Public browser check completed with no major visible issues."
    top = issues[0]
    return f"{top.get('title', 'Possible issue')} detected during a public non-invasive browser check."


def persist_scan_result(job: dict[str, Any], result: dict[str, Any]) -> str:
    audit_base_url = os.environ.get("AUDIT_BASE_URL", "https://audit.rescue.voiddo.com")
    api_base_url = os.environ.get("API_BASE_URL", "https://api.rescue.voiddo.com")
    with connect() as conn:
        with conn.cursor() as cur:
            business_id = None
            if job.get("business_name"):
                cur.execute(
                    """
                    INSERT INTO businesses(name, website_url, domain, source, status)
                    VALUES (%s, %s, %s, 'scanner_job', 'scanned')
                    RETURNING id
                    """,
                    (job["business_name"], result["url"], result["domain"]),
                )
                business_id = cur.fetchone()["id"]
            cur.execute(
                """
                INSERT INTO audits(business_id, domain, url, status, score, summary, public_slug, checked_at)
                VALUES (%s, %s, %s, 'completed', %s, %s, %s, now())
                ON CONFLICT (public_slug) DO UPDATE
                  SET status = 'completed',
                      score = EXCLUDED.score,
                      summary = EXCLUDED.summary,
                      checked_at = now()
                RETURNING id
                """,
                (business_id, result["domain"], result["url"], result["score"], _summary(result), result["public_slug"]),
            )
            audit_id = cur.fetchone()["id"]
            cur.execute("DELETE FROM audit_issues WHERE audit_id = %s", (audit_id,))
            cur.execute("DELETE FROM screenshots WHERE audit_id = %s", (audit_id,))
            for issue in result.get("issues", []):
                cur.execute(
                    """
                    INSERT INTO audit_issues(audit_id, issue_type, severity, title, public_text, internal_notes, evidence_json, recommendation)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        audit_id,
                        issue.get("issue_type", "unknown"),
                        issue.get("severity", "low"),
                        issue.get("title", "Possible issue"),
                        issue.get("public_text", ""),
                        "Generated by safe_public_scan.",
                        Jsonb(issue.get("evidence_json") or {}),
                        issue.get("recommendation", ""),
                    ),
                )
            for shot in result.get("screenshots", []):
                file_path = shot.get("file_path", "")
                public_url = ""
                marker = "/screenshots/"
                if marker in file_path:
                    public_url = f"{api_base_url}/media/screenshots/{file_path.split(marker, 1)[1]}"
                cur.execute(
                    """
                    INSERT INTO screenshots(audit_id, type, file_path, public_url, viewport)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    (audit_id, shot.get("type", "screenshot"), file_path, public_url, shot.get("viewport")),
                )
            cur.execute(
                """
                UPDATE scanner_jobs
                SET status = 'completed', audit_id = %s, result_json = %s, completed_at = now(), updated_at = now()
                WHERE id = %s
                """,
                (audit_id, Jsonb(result), job["id"]),
            )
        conn.commit()
    return str(audit_id)


def fail_scanner_job(job_id: str, error: str) -> None:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE scanner_jobs
                SET status = 'failed', error = %s, completed_at = now(), updated_at = now()
                WHERE id = %s
                """,
                (error[:1000], job_id),
            )
        conn.commit()


def process_one_scanner_job() -> dict[str, Any]:
    job = claim_scanner_job()
    if not job:
        return {"processed": False}
    try:
        result = safe_public_scan(job["url"], os.environ.get("STORAGE_ROOT", "/app/storage"))
        audit_id = persist_scan_result(job, result)
        return {"processed": True, "job_id": str(job["id"]), "audit_id": audit_id, "slug": result.get("public_slug")}
    except Exception as exc:
        fail_scanner_job(str(job["id"]), type(exc).__name__)
        return {"processed": True, "job_id": str(job["id"]), "failed": True, "error": type(exc).__name__}
