CREATE TABLE IF NOT EXISTS schema_migrations (
  filename text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO schema_migrations(filename)
VALUES
  ('001_init.sql'),
  ('002_p0_integration.sql'),
  ('003_p1_launch_gate.sql'),
  ('004_p2_mail_checkout_warmup.sql'),
  ('005_p3_checkout_manifest.sql'),
  ('006_p4_deliverability_warmup.sql'),
  ('007_warmup_calendar.sql'),
  ('008_p5_mail_signals.sql'),
  ('009_production_autonomy.sql'),
  ('010_self_operating_system.sql'),
  ('011_revenue_simulation_mail_recovery.sql'),
  ('012_scout_quality_language_gate.sql'),
  ('013_campaign_mailer_control.sql'),
  ('014_mail_clean_window_readiness.sql'),
  ('015_warmup_spacing_planner.sql'),
  ('016_warmup_spacing_rollback.sql'),
  ('017_mailer_autonomy.sql'),
  ('018_p14_customer_journey.sql'),
  ('019_p15_customer_access_monitoring.sql'),
  ('020_clean_window_rechecks.sql'),
  ('021_post_window_recheck.sql'),
  ('022_mailer_action_queue.sql'),
  ('023_mailer_closed_loop.sql'),
  ('024_recipient_resolver_audit.sql'),
  ('025_mailer_ops_runs.sql'),
  ('026_mailer_ops_run_retention.sql'),
  ('027_mailer_digest_reports.sql'),
  ('028_mailer_ops_retention_reports.sql'),
  ('029_mailer_policy_score_history.sql'),
  ('030_mailer_business_kpi_history.sql'),
  ('031_mailer_self_audit_matrix.sql'),
  ('032_scout_campaign_quality_history.sql'),
  ('033_scout_source_readiness.sql'),
  ('034_campaign_action_runs.sql'),
  ('035_lead_quality_feedback.sql'),
  ('036_post_scan_campaign_cycles.sql'),
  ('037_scanner_priority_runs.sql'),
  ('038_scanner_completion_watches.sql'),
  ('039_source_scanner_queue_runs.sql'),
  ('040_warmup_post_send_checks.sql'),
  ('041_campaign_preview_refresh_runs.sql'),
  ('042_campaign_preflight_runs.sql'),
  ('043_campaign_remediation_plans.sql'),
  ('044_campaign_remediation_executions.sql'),
  ('045_campaign_remediation_feedback_runs.sql'),
  ('046_audit_evidence_remediation_runs.sql'),
  ('047_audit_refresh_drain_runs.sql'),
  ('048_audit_refresh_completion_watches.sql'),
  ('049_audit_refresh_failure_runs.sql'),
  ('050_studio_mail_monitor.sql'),
  ('051_schema_migrations_manifest.sql'),
  ('052_contact_enrichment_runs.sql'),
  ('053_campaign_preview_reviews.sql'),
  ('054_campaign_review_remediation_runs.sql'),
  ('055_outreach_html_body.sql'),
  ('056_self_operating_closed_loop.sql')
ON CONFLICT (filename) DO NOTHING;
